name: Caller Workflow

on:
  workflow_dispatch: # This triggers the workflow manually

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is job 2"
