name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      my_variable:
        description: 'Variable to pass'
        required: true

jobs:
  call_api_trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run API Trigger Workflow
        uses: actions/checkout@v2
      
      - name: Trigger API Trigger Workflow
        uses: ./.github/workflows/api_trigger.yml
        with:
          my_variable: ${{ github.event.inputs.my_variable }}


  job2:
    needs: call_api_trigger_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is job 2"
