name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      my_variable:
        description: 'Variable to print'
        required: true

jobs:
  call_api_trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run API Trigger Workflow
        uses: actions/checkout@v2
      - name: Set Input Variable
        id: set_input
        run: echo "::set-output name=my_variable::${{ github.event.inputs.my_variable }}"

      - name: Trigger API Trigger Workflow
        uses: Workflow/.github/workflows/api_trigger.yaml
        with:
          my_variable: ${{ steps.set_input.outputs.my_variable }}


  job2:
    needs: call_api_trigger_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is job 2"
