name: Caller Workflow

on:
  workflow_dispatch

jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run Another Workflow
        uses: actions/checkout@v2
      - name: Execute Another Workflow
        run: |
          # Execute the workflow file directly
          # Replace 'path/to/another_workflow.yml' with the path to the workflow file you want to call
          /.gihtub/worfflows/api_trigger.yaml


  job2:
    needs: call_another_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is job 2"
